replicaCount: 2

image:
  repository: docker.io/venkatesh384/java-cicd-app
  tag: latest   # Jenkins will override this
  pullPolicy: IfNotPresent

serviceAccount:
  name: java-cicd-deployer

service:
  type: NodePort
  port: 8080
  nodePort: 30090

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: true
  host: java-app-new.local   # for Ingress (optional)

namespace:
  name: java-app
