replicaCount: 2

image:
  repository: venkatesh384/java-cicd-app
  tag: 21
  pullPolicy: IfNotPresent

serviceAccount:
  name: java-cicd-deployer

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: true
  host: java-app-new.local   # optional, can be ignored if only using ELB

namespace:
  name: java-app
