apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-cicd-app
  namespace: dev
  labels:
    app: java-cicd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-cicd-app
  template:
    metadata:
      labels:
        app: java-cicd-app
    spec:
      serviceAccountName: java-cicd-deployer
      containers:
        - name: java-cicd-app
          image: docker.io/venkatesh384/java-cicd-app:latest   # Jenkins will update this tag
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: java-cicd-config
                  key: APP_MESSAGE
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
