apiVersion: v1
kind: Service
metadata:
  name: java-cicd-service
  namespace: dev
  labels:
    app: java-cicd-app
spec:
  type: NodePort
  selector:
    app: java-cicd-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080  # Minikube-friendly; change if needed
