apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "springboot-helm-chart.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ include "springboot-helm-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "springboot-helm-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "springboot-helm-chart.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ include "springboot-helm-chart.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: java-cicd-config
                  key: APP_MESSAGE
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
