apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-deployer
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
