apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-app
  namespace: argocd
spec:
  project: default

  # Git repo where your Helm chart is stored
  source:
    repoURL: 'https://github.com/venkateswarluyendoti/EndtoEnd-CI-CD-Pipeline-for-Java-Application.git'
    targetRevision: main
    path: springboot-helm-chart      # folder containing Chart.yaml & templates
    helm:
      releaseName: java-app          # Helm release name

  # Kubernetes cluster & namespace for deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: java-app

  # Automated sync configuration
  syncPolicy:
    automated:
      prune: true       # Delete resources not in Git
      selfHeal: true    # Fix out-of-sync resources automatically
